# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9102030e55b30b8e8fabe2901ec1b738a288e4e34bf97b74d28205271c3a19b0625f51cf615ab618621a6b7242fb0d09be148bc5e9980dd1accd5b394b7fb7a

test:
  secret_key_base: 39a3633164d1bee573b0464f464aa8c344848f7e3d432a2006deb2943f859e0b13f0220f8b781ebc47ab9144acc0467a93ae4a40811e08fe3d1ff5e1f45c9694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
